### ISSUE TITLE
训练时候不报错，就是两分钟后就结束运行不知道为什么

### ISSUE THREAD

**Issue by wy19971004** [HaoRan-hash/DCGAN#1]

**Comment by HaoRan-hash** [comment]
老哥能把代码贴上面么，我觉得是你没修改好图片位置。

**Comment by wy19971004** [comment]
994584782 邮箱：994584782@qq.com 签名由 网易邮箱大师 定制 在2019年12月10日 17:56，HaoRan-hash 写道： 老哥能把代码贴上面么，我觉得是你没修改好图片位置。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HaoRan-hash** [comment]
你这留了个qq号，还有qq邮箱是啥意思？要我加你私聊解决么？

**Comment by wy19971004** [comment]
我从邮箱收到的信息。。直接回复了。。
    for image in glob.glob("/F:/DCGAN/faces"):     # 这里是你的图片存放地址，根据需要进行更改
        image_data = imageio.imread(image)    # 读取图片数据
        data.append(image_data)
    input_data = np.array(data)

**Comment by HaoRan-hash** [comment]
你这个很明显就是地址错误啊。。。。/F:/DCGAN/faces    你的这个地址设置前面为啥要加一个斜杠呢（你这里用的应该是绝对路径吧），绝对路径你前面还加斜杠干什么呢？直接从F盘开始就行。
而且你最后的faces应该是文件夹吧。。。。。你得faces/*啊，这样才是读取faces文件夹里面的全部图片。
你再好好理解一下我的源码

**Comment by wy19971004** [comment]
。。我也觉得是数据没加载进去。。改了好多路径，/是我最后加的，我以为*是你的文件名。。小白一个谢谢大神指导。

**Comment by HaoRan-hash** [comment]
没事，理解了就行
加油

**Comment by NaChuaN666** [comment]
老哥，我遇到这个错误，可解嘛？ ValueError: Input 0 of layer dense_1 is incompatible with the layer: expected axis -1 of input shape to have value 18432 but received

**Comment by HaoRan-hash** [comment]
应该是你送进神经网络的向量维度没处理好，你这个报错也是这个意思。
你要不把完整的错误信息贴上来，我看一下。

**Comment by NaChuaN666** [comment]
好的，这是全部的错误：
ValueError: in user code:

    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:372 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py:386 call
        inputs, training=training, mask=mask)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:976 __call__
        self.name)
    C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:216 assert_input_compatibility
        ' but received input with shape ' + str(shape))
ValueError: Input 0 of layer dense_1 is incompatible with the layer: expected axis -1 of input shape to have value 18432 but received input with shape [128, 86528]

**Comment by HaoRan-hash** [comment]
应该就是我说的维度问题，送进去的向量维度没处理好。
